# Generated by Django 4.1.2 on 2023-10-30 20:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('time_happening', models.DateTimeField()),
                ('description', models.TextField()),
                ('time_published', models.DateTimeField(default=datetime.datetime(2023, 10, 30, 20, 47, 40, 351982))),
                ('image', models.ImageField(default='static/event_photos/default.jpeg', upload_to='static/event_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(editable=False, null=True)),
                ('graduation_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'Student'), (1, 'Student Club Contact'), (2, 'Organization'), (3, 'Point of Contact')], default=0)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Clubs_and_Events.interest', to_field='tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Clubs_and_Events.user')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Clubs_and_Events.major', to_field='name')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Clubs_and_Events.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Clubs_and_Events.student')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Clubs_and_Events.interest', to_field='tag')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Clubs_and_Events.user', to_field='email'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('point_of_contact', models.CharField(max_length=30)),
                ('membersCount', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Clubs_and_Events.user')),
            ],
        ),
        migrations.CreateModel(
            name='MembersIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Clubs_and_Events.organization', to_field='name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Clubs_and_Events.user', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Clubs_and_Events.event')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Clubs_and_Events.interest', to_field='tag')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Clubs_and_Events.organization', to_field='name'),
        ),
    ]
