# Generated by Django 4.1.2 on 2023-11-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWM_Clubs_and_Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_published',
            field=models.DateTimeField(null=True),
        ),
    ]
