# Generated by Django 4.1.2 on 2023-11-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWM_Clubs_and_Events', '0002_alter_event_time_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblevents',
            },
        ),
    ]
