# Generated by Django 4.2.5 on 2023-10-14 23:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "UWM_Clubs_and_Events",
            "0002_event_interest_major_user_role_alter_user_email_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="time",
            new_name="time_happening",
        ),
        migrations.AddField(
            model_name="event",
            name="time_published",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 14, 23, 33, 1, 50076)
            ),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("membersCount", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
                (
                    "point_of_contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="UWM_Clubs_and_Events.user",
                        to_field="email",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MembersIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UWM_Clubs_and_Events.organization",
                        to_field="name",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UWM_Clubs_and_Events.user",
                        to_field="email",
                    ),
                ),
            ],
        ),
    ]
